Fix rust compiler version in CI github action
For some unknown reason, since rust 1.88.0 version, the module is
crashing with a segfault inside tokio runtime code, as soon as we
connect to an LDAP server.

Here's the crash error we get:

```
thread 'tokio-runtime-worker' panicked at /home/rdias/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.45.0/src/runtime/io/driver.rs:177:49:
misaligned pointer dereference: address must be a multiple of 0x80 but is 0x511000010240
```

To avoid this problem, we're setting the rust compiler version in our
CI infrastructure to 1.87.0.

Signed-off-by: Ricardo Dias <ricardo.dias@percona.com>